# -*- coding: utf-8 -*-
#
# TYPO3 Extension search_core_facebook documentation build configuration file, created by
# sphinx-quickstart on Thu Dec 15 16:10:27 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.extlinks',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'TYPO3 Extension search_core_facebook'
copyright = u'2016 - 2018, Daniel Siepmann'
author = u'Daniel Siepmann'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.0.1'
# The full version, including alpha/beta/rc tags.
release = u'0.0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'description': 'TYPO3 Extension to integrate facebook into search_core.',
    'github_user': 'Codappix',
    'github_repo': 'search_core_facebook',
    'github_button': True,
    'github_banner': True,
    'travis_button': False, # As long as master is not on travis
    'page_width': '1200px',
}

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    "**": ['about.html', 'globaltoc.html', 'localtoc.html', 'donate.html', 'searchbox.html', 'relations.html']
}

# Output file base name for HTML help builder.
htmlhelp_basename = 'TYPO3Extensionsearch_core_facebookdoc'

# -- Options for LaTeX output ---------------------------------------------
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'TYPO3Extensionsearch_core_facebook.tex', u'TYPO3 Extension search\\_core_facebook Documentation',
     u'Daniel Siepmann', 'manual'),
]


intersphinx_mapping = {
    'search_core': ('http://search-core.readthedocs.io/en/latest/', None),
}
extlinks = {
    'project': ('https://github.com/Codappix/search_core_facebook/projects/%s', 'Github project: '),
    'pr': ('https://github.com/Codappix/search_core_facebook/pull/%s', 'Github pull request: '),
    'issue': ('https://github.com/Codappix/search_core_facebook/issues/%s', 'Github issue: '),
}
